#!/bin/bash

# Define the options
options=("Logout/Exit Hyprland" "Suspend" "Power off" "Reboot")

# Prompt the user using dmenu
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -p "Power menu ")

# Handle the choice
case "$choice" in
    "Logut/Exit Hyprland")
        hyprctl dispatch exit
        ;;
    "Power off")
        dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true
        ;;
    "Reboot")
        dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true
        ;;
    "Suspend")
        dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true
        ;;
    *)
        echo "Invalid choice."
        ;;
esac
