#!/usr/bin/env bash

# Define the options
options=("Logout/Exit Hyprland" "Suspend" "Power off" "Reboot")

# Prompt the user using dmenu
choice=$(printf '%s\n' "${options[@]}" | rofi -config $(dirname "$0")/../conf/rofi-config.rasi -dmenu -p "Power menu ")

# Handle the choice
case "$choice" in
    "Logout/Exit Hyprland")
        if [[  -v $UWSM_WAIT_VARNAMES ]]; then
          uwsm stop
        else
          hyprctl dispatch exit
        fi 
        ;;
    "Power off")
        dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" boolean:true
        ;;
    "Reboot")
        dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true
        ;;
    "Suspend")
        dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true
        ;;
    *)
        echo "Invalid choice."
        ;;
esac
