#!/usr/bin/env bash

if [ "$ROFI_INFO" != "" ];
then
    echo "source = ../colorschemes/$ROFI_INFO.conf" > $(dirname "$0")/../hyprland.conf.d/10-colorscheme.conf
    coproc (hyprctl reload > /dev/null)
    exit 0
fi

IFS=$'\n'
colorscheme_list=($(ls -1f $(dirname "$0")/../colorschemes/*.conf | xargs -n1 basename -s .conf ))

echo -en "\0prompt\x1fChange color scheme  \n" 
echo -en "\0markup-rows\x1ftrue\n"

for colorscheme in "${colorscheme_list[@]}"
do 
  echo -en "$colorscheme\0info\x1f$colorscheme\n"
done


