#!/usr/bin/env bash

if [ "$ROFI_INFO" != "" ];
then
    coproc ( eval $ROFI_INFO > /dev/null )
    exit 0
fi

echo -en "\0prompt\x1f  \n" 
echo -en "\0markup-rows\x1ftrue\n"
eval python3 $(dirname "$0")/hyprpalette.py $@
