#!/usr/bin/env bash

#keybindings_json=[$(hyprctl -j binds | jq '.[] | select (.description!="")')]
IFS=$'\n'
keybinds=($(hyprctl -j binds | jq '.[] | select (.description!="") | .dispatcher,  .arg , .modmask, .key ,.description'))
current_array=0


convert_keycode () {
  case "$1" in
    "1")
      echo "Shift-"
      ;;
    "4")
      echo "Ctrl-"
      ;;
    "8")
      echo "Alt-"
      ;;
    "64")
      echo "Super-"
      ;;
    "65")
      echo "Super-Shift-"
      ;;
    "68")
      echo "Super-Ctrl-"
      ;;
    "72")
      echo "Super-Alt-"
      ;;
  esac
}

while (( $current_array < ${#keybinds[@]} )); do
  dispatcher_element=$(echo ${keybinds[$current_array]} | tr -d '"')
  argument_element=$(echo ${keybinds[$((current_array+1))]} | tr -d '"')
  modmask_element=$(convert_keycode $(echo ${keybinds[$((current_array+2))]} | tr -d '"'))
  key_element=$(echo ${keybinds[$((current_array+3))]} | tr -d '"')
  desc_element=$(echo ${keybinds[$((current_array+4))]} | tr -d '"')

  echo "label=$desc_element ($modmask_element$key_element);exec=hyprctl dispatch $dispatcher_element $argument_element"

  current_array=$(($current_array+5))
done
